-- Update admin user password
-- This is the hash for "Admin@123" generated by ASP.NET Core Identity
UPDATE "AspNetUsers" 
SET "PasswordHash" = 'AQAAAAEAACcQAAAAELsG2FbF6x732/gDm3Zl3iSOWNm83UoLwyD73lBEpvB4GcH6c6EeQJIQh+1SVrJbQw=='
WHERE "Email" = 'admin@parking.com'; 